---
# Playbook: Trend Micro Antiv칤rus para Oracle Linux 8
# Descri칞칚o: Instala e configura o agente Trend Micro em servidores Oracle Linux 8
# Categoria: agentes
# OS: linux
# Vers칚o: 1.1.0

- name: 游리Instala칞칚o do Agente Antiv칤rus Trend Micro游리
  hosts: all
  become: yes
  vars:
    # Estas vari치veis ser칚o substitu칤das pelos valores configurados na interface
    custom_script: false  # Definido pela interface se usar script personalizado 
    script_filename: "antivirus.sh"  # Nome do script a usar ou carregar
    script_content: ""  # Conte칰do do script personalizado se necess치rio
    temp_dir: "/tmp/trend-micro-install"
    install_dir: "/opt/ds_agent"
    log_file: "/var/log/trend_micro_install.log"
    
  tasks:
    - name: 游리Verificar se o Trend Micro j치 est치 instalado游리
      stat:
        path: /opt/ds_agent/dsa_control
      register: agent_installed
      
    - name: 游리Criar diret칩rio tempor치rio para instala칞칚o游리
      file:
        path: "{{ temp_dir }}"
        state: directory
        mode: '0755'
      when: not agent_installed.stat.exists
      
    # Fluxo para script pr칠-definido
    - name: 游리Copiar script pr칠-definido para o servidor游리
      copy:
        src: "/arquivos/linux/antivirus/{{ script_filename }}"
        dest: "{{ temp_dir }}/install.sh"
        mode: '0755'
      when: not agent_installed.stat.exists and not custom_script
      ignore_errors: yes
      
    # Fluxo para script personalizado
    - name: 游리Criar script personalizado no servidor游리
      copy:
        content: "{{ script_content }}"
        dest: "{{ temp_dir }}/install.sh"
        mode: '0755'
      when: not agent_installed.stat.exists and custom_script and script_content != ""
      
    # M칠todo alternativo caso o script n칚o seja encontrado
    - name: 游리M칠todo alternativo - Copiar script padr칚o游리
      copy:
        src: /home/opc/agents/linux/antivirus.sh
        dest: "{{ temp_dir }}/install.sh"
        mode: '0755'
      when: not agent_installed.stat.exists
      ignore_errors: yes
      
    - name: 游리Iniciar instala칞칚o do Trend Micro Antiv칤rus游리
      shell: "{{ temp_dir }}/install.sh > {{ log_file }} 2>&1"
      args:
        chdir: "{{ temp_dir }}"
      when: not agent_installed.stat.exists
      register: install_result
      async: 1800
      poll: 0
      
    - name: 游리Aguardar a conclus칚o da instala칞칚o游리
      async_status:
        jid: "{{ install_result.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 60
      delay: 30
      when: not agent_installed.stat.exists and install_result.ansible_job_id is defined
      
    - name: 游리Verificar se a instala칞칚o foi conclu칤da com sucesso游리
      command: ls -la /opt/ds_agent/
      register: install_check
      changed_when: false
      ignore_errors: yes
      when: not agent_installed.stat.exists
      
    - name: 游리Verificar se o servi칞o est치 ativo游리
      systemd:
        name: ds_agent
        state: started
        enabled: yes
      ignore_errors: yes
      when: not agent_installed.stat.exists
      
    - name: 游리Limpar arquivos tempor치rios游리
      file:
        path: "{{ temp_dir }}"
        state: absent
      ignore_errors: yes
      when: not agent_installed.stat.exists
      
    - name: 游리Status da instala칞칚o (j치 instalado)游리
      debug:
        msg: "Trend Micro Antiv칤rus j치 est치 instalado em {{ ansible_hostname }}"
      when: agent_installed.stat.exists

    - name: 游리Status da instala칞칚o (instalado agora)游리
      debug:
        msg: "Trend Micro Antiv칤rus foi instalado com sucesso em {{ ansible_hostname }}"
      when: not agent_installed.stat.exists and (job_result.finished is defined and job_result.finished)