---
- name: Playbook para configurar o arquivo /etc/hosts
  hosts: all
  become: no

  tasks:
    - name: Adiciona uma entrada no /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "192.168.1.100  meu-servidor.local"
        state: present

    - name: Verifica o conteúdo do /etc/hosts
      ansible.builtin.command: "cat /etc/hosts"
      register: hosts_content
      changed_when: false

    - name: Exibe o conteúdo do /etc/hosts
      ansible.builtin.debug:
        msg: "Conteúdo do /etc/hosts: {{ hosts_content.stdout }}"