---
- name: Coletar Informações do Host
  hosts: all
  gather_facts: yes
  become: no
  vars:
    output_format: json

  tasks:
    - name: Coletar informações básicas do sistema
      set_fact:
        system_info: "{{ ansible_distribution }} {{ ansible_distribution_version }}{% if ansible_os_family == 'Debian' %} (Debian){% elif ansible_os_family == 'RedHat' %} (RedHat){% endif %}"

    - name: Formatar informações do sistema
      set_fact:
        formatted_info:
          hostname: "{{ ansible_hostname }}"
          private_ip: "{{ ansible_default_ipv4.address | default('N/A') }}"
          system: "{{ system_info }}"

    - name: Obter IP Público
      uri:
        url: https://api.ipify.org?format=json
        return_content: yes
      register: public_ip_response
      ignore_errors: yes

    - name: Criar JSON com informações
      set_fact:
        host_details:
          hostname: "{{ formatted_info.hostname }}"
          private_ip: "{{ formatted_info.private_ip }}"
          public_ip: "{{ public_ip_response.json.ip | default('N/A') }}"
          system: "{{ formatted_info.system }}"

    - name: Debug informações coletadas
      debug:
        var: host_details
        verbosity: 0