# Arquivo de Inventário Ansible (YAML)
# Gerado automaticamente pela Automato Platform

all:
  children:
    linux:
      hosts:
        136.248.109.38:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_82_casa/inventory/ssh_keys/key_136_248_109_38
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
        168.75.100.65:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_82_casa/inventory/ssh_keys/key_168_75_100_65
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
        129.148.58.92:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_82_casa/inventory/ssh_keys/key_129_148_58_92
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
      vars:
        ansible_connection: ssh
        ansible_port: 22
    windows:
      hosts: {}
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
