# Arquivo de Inventário Ansible (YAML)
# Gerado automaticamente pela Automato Platform

all:
  children:
    linux:
      hosts:
        64.181.166.159:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_83_casa/inventory/ssh_keys/key_64_181_166_159
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
        64.181.170.171:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_83_casa/inventory/ssh_keys/key_64_181_170_171
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
        136.248.126.236:
          ansible_user: opc
          ansible_ssh_private_key_file: /home/APRESENTACAO/Beta_83_casa/inventory/ssh_keys/key_136_248_126_236
          python_interpreters:
            py39: /usr/bin/python3.9
          ansible_python_interpreter: /usr/bin/python3.9
          os_distribution: oracle
          os_version: '9'
      vars:
        ansible_connection: ssh
        ansible_port: 22
    windows:
      hosts: {}
      vars:
        ansible_connection: winrm
        ansible_port: 5986
        ansible_winrm_transport: ntlm
        ansible_winrm_server_cert_validation: ignore
